name: CI/CD for NationSounds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      
      - name: Test and build
        run: |
          # Vérifier si le script lint existe avant de l'exécuter
          if grep -q "\"lint\":" package.json; then
            npm run lint
          fi
          npm test
          npm run build
        working-directory: ./frontend
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./frontend/build

  build-backend:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nationsoundstest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, pdo_mysql
      
      - name: Install dependencies
        run: composer install --no-interaction
        working-directory: ./backend
      
      - name: Setup environment
        run: |
          cat > .env << EOF
          APP_ENV=testing
          APP_KEY=base64:$(openssl rand -base64 32)
          APP_DEBUG=true
          APP_URL=http://localhost
          
          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=nationsoundstest
          DB_USERNAME=root
          DB_PASSWORD=root
          
          CACHE_DRIVER=file
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120
          EOF
        working-directory: ./backend
      
      - name: Test
        run: |
          php artisan migrate --force
          php artisan test
        working-directory: ./backend

  security-scan:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    steps:
      - uses: actions/checkout@v4
      
      - name: Frontend security scan
        run: |
          cd ./frontend
          npm install
          npm audit --audit-level=high
        continue-on-error: true
      
      - name: Backend security scan
        run: |
          cd ./backend
          composer install --no-interaction
          composer require --dev enlightn/security-checker
          php artisan security:check
        continue-on-error: true

  deploy:
    needs: [build-frontend, build-backend, security-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./frontend/build
      
      - name: Deploy
        run: |
          echo "Déploiement en production"
          # Ajoutez vos commandes de déploiement ici
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
